### ISSUE TITLE
Record IDs documentation shows duplicate example

### ISSUE THREAD

**Issue by HenningEng** [surrealdb/www.surrealdb.com#110]
For some reason the Text Record IDs shows the same code as Numeric Record IDs at
https://surrealdb.com/docs/surrealql/datamodel/ids

Looks different in the file on the main branch, unless I'm looking on the wrong file or branch?
It states "CREATE company:surrealdb SET name = 'SurrealDB';"
[app/templates/docs/surrealql/datamodel/ids.hbs](https://github.com/surrealdb/www.surrealdb.com/blob/0b61abafc43ce38b34f2e9bcad339c6f27a54272/app/templates/docs/surrealql/datamodel/ids.hbs#L19)

![image](https://user-images.githubusercontent.com/73801058/231746209-00e425cc-b3f0-491c-a688-b13365fe0cf9.png)

**Comment by kearfy** [comment]
This has since been fixed. Thanks for pointing it out!
