### ISSUE TITLE
Documentation: Java library exists now or not?

### ISSUE THREAD

**Issue by FilipJirsak** [surrealdb/www.surrealdb.com#126]
### Description

On the [Libraries](https://surrealdb.com/features#libraries) page, there is Java library shown as available.
But the [Integration – Libraries](https://surrealdb.com/docs/integration/libraries) page says Java library is not available yet.

Which one is right?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by finnbear** [comment]
Thank you for pointing this out! The Java library exists [here](https://github.com/surrealdb/surrealdb.java), although usage requires following [these instructions](https://github.com/surrealdb/surrealdb.java/issues/2#issuecomment-1268787466) until JARs/packages are published.

I have transferred the issue to the website repository as that is where the inconsistency should be resolved.

**Comment by kearfy** [comment]
The docs for the Java driver have since been published, closing this issue. Thanks!
