### ISSUE TITLE
SurrealQL datamodel descriptions wrong

### ISSUE THREAD

**Issue by w1ll-i-code** [surrealdb/www.surrealdb.com#139]
On this page: https://surrealdb.com/docs/surrealql/datamodel, the description for UUIDs, Objects and Arrays says `Datetimes and durations can be used to store and manipulate dates and times` instead of their proper descriptions.

**Comment by kearfy** [comment]
Linking to #129 as this is fixed in that PR and a lot of content related to this subject has changed in that PR

**Comment by kearfy** [comment]
This issue has since been resolved in c8cc6882cf599b0e7bfcb87202f964150cdcacb1
