### ISSUE TITLE
Bug: docs arent following WCAG standards

### ISSUE THREAD

**Issue by ImLunaHey** [surrealdb/www.surrealdb.com#155]
### Describe the bug

The main website for this project uses a colour scheme that is not colourblind-friendly.

![image](https://github.com/surrealdb/surrealdb/assets/105922175/753a1dcd-7ad5-4ceb-a98b-e17e06c70454)

![image](https://github.com/surrealdb/surrealdb/assets/105922175/20c7ac4e-90a0-495b-b6ea-470b2be7db07)

### Steps to reproduce

1. Be colourblind
2. Go to site
3. Cry as you can't read the docs

### Expected behaviour

1. Be colourblind
2. Go to site
3. Be able to read the text

### SurrealDB version

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hi @ImLunaHey, thanks for pointing this out! I moved the issue to the repository for the website!

**Comment by Ekwuno** [comment]
Hey @ImLunaHey I know this took so long to get to, as we were ramping up to a redesign of the website and a 1.0 release.

My apologies for the long wait but I am happy to say that our new website has fixed most of our contrast issues and while we know that there are still some improvements to be made. We are committed to fixing them in the coming weeks. I'll close this issue as we will be opening some more RE: Accessibility. 

<img width="1408" alt="Screenshot 2023-10-08 at 12 30 50" src="https://github.com/surrealdb/www.surrealdb.com/assets/35943047/c75e0336-86d6-472b-9bdb-c0abb403ced0">

**Comment by ImLunaHey** [comment]
Changes look good 🥳 

Should these not be only shown when focused by keyboard? 🤔 

Seems a tad odd to see them when clicking.
![image](https://github.com/surrealdb/www.surrealdb.com/assets/105922175/2cd90204-dc34-4c05-8c3c-ceb391a36f53)

**Comment by Ekwuno** [comment]
You're on Firefox right? I'm not sure why that happens on Firefox but on any other browser,It's alright. I'll look I to it but like I said. More improvement are coming.
