### ISSUE TITLE
[ Bug ] Error in connection to google analytics 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [surrealdb/www.surrealdb.com#163]
When we open the home page we have linked it to google analytics to track our traffic but due to some issue, it's not getting connected. 
![image](https://github.com/surrealdb/www.surrealdb.com/assets/76584243/c6d98dd8-620b-4c65-ab61-82fb4c9aae60)

I would love to fix this issue as I have worked with google analytics multiple times. Have setup this website on my local system. Please assign me this issue so can create a PR. 

thanks!

**Comment by tobiemh** [comment]
Hi @rohan-kulkarni-25 you can find the file here: https://github.com/surrealdb/www.surrealdb.com/blob/main/aws/viewer-response/index.js

**Comment by tobiemh** [comment]
This should have been fixed and working for a while now. Closing this issue, but reopen if there are any additional problems 🚀 !
