### ISSUE TITLE
Documentation: Create a quick reference for pre-defined parameters

### ISSUE THREAD

**Issue by jquesada2016** [surrealdb/www.surrealdb.com#180]
### Description

Currently, there are many variables, such as `$auth`, `$value`, and others that appear throughout the documentation, but are not easily found in a single place. Moreover, there are variables that seem to exist, but are not documented anywhere, such as `$session`, nor a mechanism to view all parameters available to the current connection.

I believe it would be a great idea to place all available variables in their own dedicated documentation page, or perhaps within the already existing `Params` page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by finnbear** [comment]
Good idea :+1: 

I've transferred this to the website repository where user-facing documentation is written.

**Comment by kearfy** [comment]
@Odonno kindly opened a PR for this just two days ago!
