### ISSUE TITLE
Set anchors and anchor links

### ISSUE THREAD

**Issue by Odonno** [surrealdb/www.surrealdb.com#188]
There are some anchors but not everywhere.
Also add anchor link to set anchor (to copy link).

I can work on this if you want.

**Comment by Ekwuno** [comment]
Oh, I see what you mean! That would be really helpful.  I have a PR open for some Semantic improvements around links if you want to take a look https://github.com/surrealdb/www.surrealdb.com/pull/189/files it's in draft at the moment. 

Also the website does need a lot of accessible improvements. Please feel free to make PRs

**Comment by tobiemh** [comment]
This should now be fixed with the launch of the new documentation site: https://docs.surrealdb.com 🚀 !
