### ISSUE TITLE
Provide a visual model

### ISSUE THREAD

**Issue by dodalovicgran** [surrealdb/www.surrealdb.com#236]
To understand what's being presented, it would be nice to have a visual diagram of how the things look in the db.

https://github.com/surrealdb/www.surrealdb.com/blob/2f2e11699a3024a371d05cc2fcaba91423a04f88/app/templates/docs/integration/sdks/rust.hbs#L28

**Comment by Ekwuno** [comment]
Hi @dodalovicgran thanks for pointing this out. We do have plans of adding some diagrams to the docs. Currently @timpratim is working on some infographics that will also go into docs.

**Comment by dodalovicgran** [comment]
Great, @Ekwuno 
I'm looking forward to it!
