### ISSUE TITLE
Adding the missing documentation 

### ISSUE THREAD

**Issue by oricc** [surrealdb/www.surrealdb.com#24]
Hi,
I've recently discovered this project and it's gotten me really excited!
While trying to use it, I've found myself often looking in the code to figure out how to perform certain operations, and I would like to both contribute and make the project more accessible by documenting what I've found in the official docs.

How can I start writing docs? Is there a convention to them? What are the most important missing docs?

Thanks!

**Comment by MatthewAry** [comment]
1. Create a fork of this repo.
2. Clone Repo
3. Run `npm i`
4. Run `npm run start`
5. modify files found in app/templates contains page contents.
   - app/router.js contains the site router which is needed to add pages.
6. Create PR to this project with your changes.
