### ISSUE TITLE
Documentation: Integration of Node.js SDK - typo

### ISSUE THREAD

**Issue by gander** [surrealdb/www.surrealdb.com#251]
### Description

https://surrealdb.com/docs/integration/sdks/nodejs

Wrong:
```js
let updated = await db.change("person:jaime", {
    marketing: true,
});
```

Correct:
```js
let updated = await db.update("person:jaime", {
    marketing: true,
});
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hi @gander, thanks for letting us know! I'll be patching this soon!
