### ISSUE TITLE
Documentation: SELECT statement

### ISSUE THREAD

**Issue by gander** [surrealdb/www.surrealdb.com#252]
### Description

Need a specific example of the data being queried on and what the result should be. You could also prepare an importable file on which to experiment, and then it would be enough to show only the results of the given queries.

If the issue https://github.com/surrealdb/surrealdb/issues/2380 is incorrect, examples would allow to stop reporting bugs.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexFrid** [comment]
I see what you mean @gander

The plan is to eventually make all the examples in the docs executable.

It will take some time to get to that stage however.

In the meantime, we have the demo dataset, which was just released which you can import.
And the examples in the docs will be updated in due course to reflect that or another demo dataset.

As @kearfy said, there will also be some queries added there.

Was there anything specific you had in mind or just generally having the data form the docs examples?

**Comment by gander** [comment]
@AlexFrid @kearfy 

I wanted the demo data to be enough to run the examples from the site. Or at least that the examples have given results, which would already to some extent direct me to what the data structure should look like.

**Comment by AlexFrid** [comment]
Makes sense. We are working towards that.
