### ISSUE TITLE
Feature: Edit on GitHub / Suggest Changes to this Page button

### ISSUE THREAD

**Issue by LeoDog896** [surrealdb/www.surrealdb.com#327]
### Is your feature request related to a problem?

It is hard to suggest changes to docs without navigating the GitHub organization

### Describe the solution

It may be a good idea to have a sort of "Edit on GitHub" or "Suggest Changes to this Page" button somewhere on each [doc](https://surrealdb.com/docs/) page, like how [Vite](https://vitejs.dev/guide/) has it.

### Alternative methods

Navigate the GitHub organization

### SurrealDB version

docs

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LeoDog896** [comment]
(for #326)

**Comment by Ekwuno** [comment]
I think we have this already. It shouldn't be hard to do. The GitHub component we have should allow for this. @akankshadharkar do you want to handle this?

**Comment by akankshadharkar** [comment]
I missed this tag, my apologies. 
Yes certainly - it's quite easily doable. 

However, my question is if we want to make the changes now given that we're in the process of migrating our docs @Ekwuno?

**Comment by Ekwuno** [comment]
We already have this feature implemented in docs.  Adding  ``` <Link @link={{github}}>edit this file on GitHub</Link> ``` to each page would solve this.  @LeoDog896 I might not be able to prioritise this as we are migrating the docs to a more stable platform that comes with this feature baked in.

**Comment by LeoDog896** [comment]
Alright :+1:
