### ISSUE TITLE
Documentation Typos

### ISSUE THREAD

**Issue by tetotechy** [surrealdb/www.surrealdb.com#33]
A collection of typos:

**Validation Functions**
In the first `is::alpha` example (`SELECT * FROM is::alpha("ABC123");`) the output should be `false`

**JS-based Client Libraries (both Deno and Node on the server-side and JavaScript on the client side)**
In the code, in the `// Perform a custom advanced query` example, there is a missing `$` before the `tb` identifier in the query string

**Deno driver**
In the code for the `Surreal.Instance` example, the `Surreal` module is imported `cjs`-style, not `ESM`-

Thanks for the hard work! Keep it up!

**Comment by tobiemh** [comment]
Thanks for finding these @tetotechy 😀👍!
