### ISSUE TITLE
Documentation: Demo Data Diagram is hard to read

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/www.surrealdb.com#338]
### Description

The demo data diagram was recently updated and has become harder to comprehend.

> In the diagram below, the nodes in pink are the [standard tables](https://surrealdb.com/docs/surrealql/statements/define/table), the ones in purple represent the [edge tables](https://surrealdb.com/docs/surrealql/statements/relate) which shows relationships between records and SurrealDB as a graph database. While the nodes in gray are the [pre-computed table views](https://surrealdb.com/docs/surrealql/statements/define/table)

Before:
![image](https://github.com/surrealdb/www.surrealdb.com/assets/157217/52ee0c8a-b4ff-448c-a49c-86842bc94c1b)

After:
![image](https://github.com/surrealdb/www.surrealdb.com/assets/157217/70eebf91-55be-447b-862c-4aae26e044b8)

The colors now have exceptionally poor contrast and distinguishing edges from nodes has become difficult.

Recommendations:
- For technical diagrams, function must be prioritized over aesthetics
- Use high contrast colors to delineate between object types.
- Prioritize Text Legibility. 
  - Don't use gradients on text.
  - Don't use fonts that compromise legibility (Such as the font used in the SurrealDB Logo). Conventional fonts are best.
- Gradients may be used but as a general rule, it should affect luminosity only, otherwise it can become unclear what the intended color is supposed to be.
- Consider (WCAG) 2.1 guidelines and [using a contrast checker](https://webaim.org/resources/contrastchecker/)

Tagging: @jaimemh https://github.com/surrealdb/www.surrealdb.com/commit/68e7a7c769ac6e6b6cae8d35ab38e4ffb012df8a

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
Hi @MatthewAry thanks for pointing this out. I realised yesterday that this was updated will get this reverted. I agree with all the recommendations you have made. Will follow up on this
