### ISSUE TITLE
Documentation: filters and the tokenizers

### ISSUE THREAD

**Issue by emmanuel-keller** [surrealdb/www.surrealdb.com#341]
### Description

The filters and tokenizers parameters are listed, but not everything is fully documented.

https://surrealdb.com/docs/surrealql/statements/define/analyzer

Things that are not covered: 

- Edgengran takes 2 parameters, `min` and `max`. They are not explained. Eg.: `edgengram(2, 5)`
- Snowball takes 1 parameter: The name of the language.  `snowball(french)`. It also changes the case to lowercase.
- Real examples for each tokenizer and filter.

blank: 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
They're documented from what I see on the Page. Can you add more detail please so I can update accordingly if need. 
<img width="958" alt="Screenshot 2023-10-08 at 12 23 12" src="https://github.com/surrealdb/www.surrealdb.com/assets/35943047/f4558ce7-cf34-47b5-91d1-e109a29bb56a">

**Comment by emmanuel-keller** [comment]
@Ekwuno Description updated!

**Comment by DanikVitek** [comment]
The `ngram` filter is not mentioned in the docs, thought exists and works
