### ISSUE TITLE
Documentation: Add nested  `IF ELSE` example in documentation 

### ISSUE THREAD

**Issue by cerasusK** [surrealdb/www.surrealdb.com#343]
### Description

The version `1.0.0.-beta 10`  introduced "Less bulky IF-ELSE statements".

[The documentation](https://surrealdb.com/docs/surrealql/statements/ifelse) should reflect that, with a longer example snippet than given in the release announcement

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
Hey @cerasusK I'm not sure what you mean by a longer example snippet, the snippet here sufficiently shows an example for what an `if else` statement can be used for within the context of SurrealDB to define conditions. 

Also, this statement is mostly on a use case bases for conditions within queries. 

Is there a specific use case you want to see in this section?

**Comment by cerasusK** [comment]
![grafik](https://github.com/surrealdb/www.surrealdb.com/assets/9279755/5fa57ee5-b90a-4ecc-9f49-0e211a8e7488)

the snippet in [the release announcement](https://surrealdb.com/releases#v1-0-0-beta-10)

showcases only an `IF` block. For completeness' sake an `ELSE IF`and `ELSE` should be included, I believe.

[The current documentation](https://surrealdb.com/docs/surrealql/statements/ifelse) also does not demonstrate multiple statements inside one block.

**Comment by Ekwuno** [comment]
Gotcha! I will add a nested If else example. Renamed the Issue so it's clearer
