### ISSUE TITLE
Documentation: surrealdb.node describes the signin method incorrectly

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/www.surrealdb.com#356]
### Description

https://surrealdb.com/docs/integration/sdks/nodejs#signin shows the signature for the method as requiring an object with the signature of something like
```ts
type SuperUserAuth = {
	user: string;
	pass: string;
};

type NamespaceAuth = {
	NS: string;
	user: string;
	pass: string;
};

type DatabaseAuth = {
	NS: string;
	DB: string;
	user: string;
	pass: string;
};

type ScopeAuth = {
	NS?: string;
	DB?: string;
	SC: string;
	[T: string]: unknown;
};

export type AnyAuth = SuperUserAuth | NamespaceAuth | DatabaseAuth | ScopeAuth;
```
But in reality, it seems that the signature should be
```ts
type SuperUserAuth = {
	username: string;
	password: string;
};

type NamespaceAuth = {
	namespace: string;
	username: string;
	password: string;
};

type DatabaseAuth = {
	namespace: string;
	database: string;
	username: string;
	password: string;
};

type ScopeAuth = {
	namespace?: string;
	database?: string;
	scope: string;
	[T: string]: unknown;
};

export type AnyAuth = SuperUserAuth | NamespaceAuth | DatabaseAuth | ScopeAuth;
```
I believe this is because the https://github.com/surrealdb/surrealdb.node project now uses the wasm library instead of https://github.com/surrealdb/surrealdb.js 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
I know we alias username and user in some cases but i will look into this. :)
