### ISSUE TITLE
Documentation: Wrong project link in node sdk docs

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/www.surrealdb.com#357]
### Description

On https://surrealdb.com/docs/integration/sdks/nodejs the part where it says

> To contribute to the SDK code, [submit an Issue or Pull Request here](https://github.com/surrealdb/surrealdb.js).

Is linking to the wrong project page. It should be changed to point to https://github.com/surrealdb/surrealdb.node

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akankshadharkar** [comment]
Thanks for pointing that out, updating it now :)
