### ISSUE TITLE
Sidebar hidden when innerWidth is <=1024

### ISSUE THREAD

**Issue by gusutabopb** [surrealdb/www.surrealdb.com#37]
Documentation sidebar is not visible/accessible on mobile. Because of this I couldn't find any of the documentation that was not directly linked from the "Overview" page (e.g. "SurrealQL", "CLI tool", sections).

<img width="525" alt="Screen Shot 2022-09-21 at 13 12 47" src="https://user-images.githubusercontent.com/4231387/191412995-24fb9c61-0d4b-4570-9e14-12efedf1ac9d.png">
<img width="525" alt="Screen Shot 2022-09-21 at 13 12 29" src="https://user-images.githubusercontent.com/4231387/191413006-a4888e21-bb71-4070-9be3-290c6b085e23.png">

**Comment by MatthewAry** [comment]
I think I will try to implement a workaround in a PR but it's not going to make that sidebar appear.
