### ISSUE TITLE
Bug: Contact page returns 404

### ISSUE THREAD

**Issue by dodanex** [surrealdb/www.surrealdb.com#38]
In the website footer there is a link called `Status` pointing to https://status.surrealdb.com/
On this page there is a button called `Get in touch` pointing to https://surrealdb.com/contact 

THE PROBLEM: The Contact page returns 404 error. I also couldn't find the Contact link anywhere else on the website.
THE SOLLUTION: Replace the button link with something else or create the Contact page.

**Comment by tobiemh** [comment]
Hi @dodanex thanks for this 😀👍 ! I've temporarily remove the link to the contact page!
