### ISSUE TITLE
Missing information on functions for JS related clients

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/www.surrealdb.com#40]
Per https://github.com/surrealdb/surrealdb.js/blob/411cb95e707459f749d790bab509891a17119a6b/src/index.ts there are a number of methods missing documenation:
- sync https://github.com/surrealdb/surrealdb.js/blob/411cb95e707459f749d790bab509891a17119a6b/src/index.ts#L249
- ping https://github.com/surrealdb/surrealdb.js/blob/411cb95e707459f749d790bab509891a17119a6b/src/index.ts#L274
- live https://github.com/surrealdb/surrealdb.js/blob/411cb95e707459f749d790bab509891a17119a6b/src/index.ts#L371
- kill https://github.com/surrealdb/surrealdb.js/blob/411cb95e707459f749d790bab509891a17119a6b/src/index.ts#L385
- info https://github.com/surrealdb/surrealdb.js/blob/411cb95e707459f749d790bab509891a17119a6b/src/index.ts#L302

Would like to see information about these methods on:
- https://surrealdb.com/docs/integration/libraries/webassembly
- https://surrealdb.com/docs/integration/libraries/nodejs
- https://surrealdb.com/docs/integration/libraries/deno
- https://surrealdb.com/docs/integration/libraries/javascript

**Comment by MatthewAry** [comment]
In addition, it would be good to include details about the classed found in here:
https://github.com/surrealdb/surrealdb.js/tree/411cb95e707459f749d790bab509891a17119a6b/src/classes

**Comment by mathe42** [comment]
1. for info I agree rest is for live queries that are currently disabled by surrealdb so no need to document it,
2. I think only 1 lib page for nodejs / deno / js with dedicated install instructions for each.
3. The classes (except for Live) are not part of the exposed API surface. The Emitter class is only used by Live + main class so it is a good idea to document it.
