### ISSUE TITLE
Bug: Missing JavaScript icon

### ISSUE THREAD

**Issue by gander** [surrealdb/www.surrealdb.com#406]
### Describe the bug

![image](https://github.com/surrealdb/www.surrealdb.com/assets/421597/c3e40091-d959-4157-90cb-769a8427b254)

### Steps to reproduce

Visit https://surrealdb.com/docs

### Expected behaviour

View proper JavaScript Icon

### SurrealDB version

n/a

### Contact Details

notck76v@duck.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
This has been resolved. Thanks for filling an issue.
