### ISSUE TITLE
Documentation: Example usage for `surreal start` shows `surreal version` instead

### ISSUE THREAD

**Issue by cerasusK** [surrealdb/www.surrealdb.com#417]
### Description

Example usage for `surreal start` shows `surreal version` instead

See: https://docs.surrealdb.com/docs/cli/start#example-usage

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
@cerasusK I can see how this might be confusing but we added that there to show the version before running start so that people know what version they are on. I can change the wording so it is less confusing.
