### ISSUE TITLE
Add Examples to the `DEFINE` statement

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/www.surrealdb.com#48]
At the time of writing https://surrealdb.com/docs/surrealql/statements/define only shows the syntax and provides no examples. Please add examples of how the define statement can be used to accomplish different objectives.

Define is a VERY powerful feature and may deserve several sub-pages as well to deal with it's different features.
These sub-pages may include using `DEFINE` with:
- `NAMESPACE`
- `DATABASE`
- `LOGIN`
- `TOKEN`
- `SCOPE`
- `TABLE`
- `EVENT`
- `FIELD`
- `INDEX`
- 'LINKS` - per https://discord.com/channels/902568124350599239/1018618253695795261/1026900902877069353

These sub-pages may include specific use-case examples describing how one could accomplish common objectives.

**Comment by DarkGhostHunter** [comment]
I think that is needed too, but some sections regarding the `DEFINE` statement should be their own. For example, `DEFINE LOGIN` should be in an authentication section, along with `SCOPE`. The `DEFINE TABLE` and `DEFINE FIELD` should be on the Schemafull section, and so on.
