### ISSUE TITLE
Add Authentication section

### ISSUE THREAD

**Issue by DarkGhostHunter** [surrealdb/www.surrealdb.com#50]
Being SurrealDB a database that is expected to be exposed for frontend apps, it seems that is necessary a section for authentication and authorization.

It should, at least, contain the following topics:

- Why you should secure your database access
- How to create an user to map authentication
- How to allow creating an user dynamically
- How to map authorization (permissions) over an user

**Comment by Ekwuno** [comment]
Took us long enough but https://surrealdb.com/docs/security

**Comment by DarkGhostHunter** [comment]
That's better than I imagined.
