### ISSUE TITLE
`SELECT` statement syntax makes no mention of `AS`

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/www.surrealdb.com#59]
I recently saw a message posted on Discord where someone was struggling with a bug in SurrealDB that was being made manifest by a `SELECT` statement they wrote. The bug is not related to this issue, but what is related is that they weren't sure that they could make an alias using the `AS` keyword in a query, which they could do. 

I noticed that `AS` is missing from the official documented syntax for the `SELECT` statement on the website. I think this should be fixed.

**Comment by Ekwuno** [comment]
I can see some examples using the `AS` keyword in docs now https://surrealdb.com/docs/surrealql/statements/select
