### ISSUE TITLE
Enhancement: remove the `user@localhost` prefix in front of commands in `Installation`

### ISSUE THREAD

**Issue by KittyBorgX** [surrealdb/www.surrealdb.com#64]
Currently, the code block for installation in https://surrealdb.com/docs/start/installation looks something like this: 

![Screenshot 2022-11-08 at 9 47 46 AM](https://user-images.githubusercontent.com/82328083/200473982-939486b8-8755-4c7e-b0d3-5940f24d7072.png)

In interest of the first time users and for user experience, I feel it is better to remove the `user@localhost` prefix and either keep the command only or keep it with the `%` prefix. This will also make it easier to copy-paste directly without giving much thought to it. 

I'm willing to take up the implementation and open a pull request if this Enhancement gets approved.

**Comment by ank1traj** [comment]
Can I assign this to myself?

**Comment by Ekwuno** [comment]
Apologise for the none response, we will be implementing a copy to clipboard that will ignore that prefix
