### ISSUE TITLE
Enhancement: Add link to available libraries

### ISSUE THREAD

**Issue by MagnusHJensen** [surrealdb/www.surrealdb.com#68]
Currently the libraries section look like this:
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/32039051/205107141-7f15e370-f9dd-4d73-99ad-7b94e73836b1.png">

It would be nice if the header was clickable which took you to the GitHub repository for that specific library.

**Comment by ank1traj** [comment]
Can I assign this to myself?

**Comment by tobiemh** [comment]
Hey @ank1traj definitely - that would be amazing!

**Comment by ank1traj** [comment]
@tobiemh Assign this to me so that I can start working on the same.

**Comment by ank1traj** [comment]
@tobiemh There is already a link for GitHub and documentation beneath the specific library. Should we add link to the header too?

![image](https://user-images.githubusercontent.com/32160084/211018736-ec0bed39-06af-4894-b3f0-a2dba09ff9cd.png)

**Comment by tobiemh** [comment]
Hi @ank1traj does it affect the styling if you link the headers?

**Comment by ank1traj** [comment]
@tobiemh not at all

**Comment by kearfy** [comment]
We now link to the respective github repositories on the driver detail pages, closing this issue!
