### ISSUE TITLE
[Enhancement] Add Scoop installation instructions to the website.

### ISSUE THREAD

**Issue by Zliced13** [surrealdb/www.surrealdb.com#76]
Surrealdb has been added to [Scoop](https://scoop.sh/), a command line installer for windows.

The instructions to install it with Scoop are very simple:
```pwsh
scoop install surrealdb 
```

The instructions should be added to this section of the official website.
![(firefox)k5A8v8_02-03-2023](https://user-images.githubusercontent.com/101912712/216713507-0c279803-94c9-4c83-a036-52e93bceaeec.jpg)

**Comment by Ekwuno** [comment]
https://surrealdb.com/docs/installation/windows
