### ISSUE TITLE
surrealdb.dev shows up in search results and is out of date

### ISSUE THREAD

**Issue by rgarlik** [surrealdb/www.surrealdb.com#85]
Hey all,

While searching the internet for "querying SurrealDB" I came across this broken documentation site as the first result: https://surrealdb.dev/docs/start/querying-surrealdb

The URL is surrealdb.dev instead of surrealdb.com. I'm not sure why this site exists but my assumption is that either it shouldn't be indexed by search engines at all or it should redirect to surrealdb.com

It can be confusing because the two sites look identical.

**Comment by rgarlik** [comment]
Sorry, I'm not sure what the XML file you posted is.

Indexing could be prevented by using the following `robots.txt`:
```
User-agent: *
Disallow: /
```

**Comment by tobiemh** [comment]
This is complete 🚀 !
