### ISSUE TITLE
Release page has incorrect information

### ISSUE THREAD

**Issue by careerlister** [surrealdb/www.surrealdb.com#96]
For the Beta 9 release section (https://surrealdb.com/releases#v1-0-0-beta-9) the content for "Support code blocks and advanced expressions" is a repeat of the "Add support for selecting ranges of records"'s section's content.

**Comment by kratess** [comment]
I don't see the redundancy you are talking about. Does the issue has been fixed?

**Comment by kratess** [comment]
> For the Beta 9 release section (https://surrealdb.com/releases#v1-0-0-beta-9) the content for "Support code blocks and advanced expressions" is a repeat of the "Add support for selecting ranges of records"'s section's content.

I don't see the redundancy you are talking about. Does the issue has been fixed?

**Comment by careerlister** [comment]
Looks to have been fixed.
